### ISSUE TITLE
Brand Refresh: Logo/Colors/Typography

### ISSUE THREAD

**Issue by mcturco** [asyncapi/brand#1]
I am proposing that we improve the AsyncAPI brand to better fit the trends of the industry as well as to establish a boilerplate for a design system (I will create a separate repo for this once we are in a good place with the brand) and eventually a UI kit. The brand refresh is the first step in the process of creating a brand structure for expected growth in the future.

In this issue, I will be working on the following:

- Small adjustments to the logo
- Redefining the color palette of AsyncAPI
- Typography
- Establish tone

**Please note:** These changes are intended to be subtle so as not to affect current brand recognition.

I will document my process in this issue and will be looking for feedback from those who are interested in being part of the process! :)

**Comment by mcturco** [comment]
I am super happy to announce this first step in the brand refresh process for AsyncAPI! Please click on this video link to watch my presentation:

https://www.loom.com/share/ad3e8b948c214ff3847caac42e28f650

I would appreciate any feedback that you may have!

If you would like to view the slides from this presentation, please [click here.](https://www.figma.com/proto/yLZsxymcotx0mUwy5Pc7xB/Brand?page-id=0%3A1&node-id=2%3A2&viewport=241%2C48%2C0.25&scaling=contain&starting-point-node-id=2%3A2)

**Comment by mcturco** [comment]
Here's the new logo in case you missed it in the recording :)

![AsyncAPI_NewLogo](https://user-images.githubusercontent.com/60163079/145466828-e2c8a2d4-eec8-40e5-a8aa-93298a714e60.jpg)
![AsyncAPI_NewLogo_Gradient](https://user-images.githubusercontent.com/60163079/145466866-b2806ade-32c9-4939-92f3-f511fff069d7.jpg)
![AsyncAPI_NewLogo_Outline](https://user-images.githubusercontent.com/60163079/145466881-1732cf7d-8510-46bf-843d-ea55a210ba19.jpg)

**Comment by derberg** [comment]
LOVE IT ❤️ 

not to mention great explanation and all the bits and pieces you were thinking about. 
and btw, I'm so happy this strange broken `c` is not there anymore 😅

**Comment by alequetzalli** [comment]
+1 ❤️

**Comment by magicmatatjahu** [comment]
Awesome :heart: 

Logo shape, dark mode as well as the tooling branding idea, I loved it! Awesome work :clap: 

After watching recording I have some ideas:
- branding tool (I love it ❤️  2x) - we should try to "categorize" given tool to some category. What I mean? Atm we have some UI projects (Studio, React component, some parts of Cupid), projects that focus on spec, including validation, transforming etc (ParseJS, Diff, Optimizer, Converter, in the future Bundler as well), projects that focus on creating something based on spec, but it's not related to UI (like Generator and its templates, Modelina to produce models, Event Gateway, Server API etc) for that each category I think that we should "reserve" a certain color:
- UI category - pink/magenta
- Spec based tools - yellow
- Creating something from spec tools - blue
- Other tools that are very hard to categorize, like Glee or CLI - green

Then we will have an easier task to define what is what. What do you think? :) 

Can't wait to see the style guide for the UI, padding, margins etc 🚀

**Comment by jonaslagoni** [comment]
Love it, personally, I love the all-white box where the internal logo is colored (no idea how to explain it, the middle one 😆) 🚀 

I absolutely love the branding of tooling ideas, if that can be mastered correctly, just looking at the colors gives an indication of what it does!

About the mascot, I gotta admit it is not something I have ever given any thought. However, if it can be well executed it can probably resonate with a lot more people 👍

**Comment by fmvilas** [comment]
> About the mascot, I gotta admit it is not something I have ever given any thought. However, if it can be well executed it can probably resonate with a lot more people 👍

Agree. Luckily I already thought about it.

![Captura de pantalla 2021-12-10 a las 13 15 01](https://user-images.githubusercontent.com/242119/145573596-4566760a-5a89-4f84-9ecc-039e89645f7c.png)

**Comment by mcturco** [comment]
> I'm so happy this strange broken c is not there anymore 😅

@derberg that "c" had an underbite like a bull dog

**Comment by mcturco** [comment]
> Logo shape, dark mode as well as the tooling branding idea, I loved it! Awesome work 👏

Thank you, @magicmatatjahu 🥳  🎉 

> each category I think that we should "reserve" a certain color:

I think this is a great idea! I will definitely keep this in mind when working through the branding of the tooling!! Thank you for your feedback!

**Comment by mcturco** [comment]
> Love it, personally, I love the all-white box where the internal logo is colored (no idea how to explain it, the middle one 😆) 🚀

Thanks for your kind feedback, @jonaslagoni 😄  And yes, I definitely like the look of that version too!

> I absolutely love the branding of tooling ideas, if that can be mastered correctly, just looking at the colors gives an indication of what it does!

Yes, this is very similar to what @magicmatatjahu was saying. I will definitely keep that in mind!

> About the mascot, I gotta admit it is not something I have ever given any thought. However, if it can be well executed it can probably resonate with a lot more people 👍

Agreed! I think if done right we can have a mascot that has meaning and relates to the specification. I will give this one some thought for sure!

**Comment by mcturco** [comment]
@fmvilas That had me dying 🤣  "dEsIgN iS mY pAsSiOn" 👍 

I also can't help but think of this:
![image](https://user-images.githubusercontent.com/60163079/145591403-fd0ca968-0f3f-4cd1-a2aa-838a8f95bb32.png)

**Comment by fmvilas** [comment]
> I also can't help but think of this:

Haha! Exactly! Same happened to me after I posted it 😅 

> each category I think that we should "reserve" a certain color:

That's a cool idea. I wonder if we can come up with a different gradient for each tool instead of each category. Or maybe gradients of similar colors? In any case, something to think about afterward, don't want you to bloat this issue up.
