### ISSUE TITLE
ownership of brand

### ISSUE THREAD

**Issue by derberg** [asyncapi/brand#102]
after having a chat with @mcturco I learned she can no longer have responsibility here, only can act as support whenever new owner needs some help, especially some history background knowledge.

Missy suggested @Mayaleeeee as new owner

cc @fmvilas

**Comment by Mayaleeeee** [comment]
Thank you @derberg 
I'm happy to take up the responsibility.

**Comment by mcturco** [comment]
I agree! @Mayaleeeee is more involved than I am able to be right now :)

**Comment by Mayaleeeee** [comment]
> Thanks @mcturco 🙏 
> 
> @Mayaleeeee can you open a PR please, with proper change in codeowners?

@derberg 
No problem at all! I'll take care of it and let you know if I need any help. 

Thanks!
