### ISSUE TITLE
Would love to get some marketing materials for `Let's talk about contributing` live stream

### ISSUE THREAD

**Issue by derberg** [asyncapi/brand#21]
#### Reason/Context

As part of the efforts to make it easier for people to contribute to the project, we are running regular live stream sessions about it.
It would be nice to create some marketing materials that we could easily reuse for the sessions.

Playlist for more context: https://www.youtube.com/playlist?list=PLbi1gRlP7pigPBrBMaNQhUeniR1pdDMiY

We are not in rush here. This is why I mark it as a `good first issue` in case there is someone in the community that would like to join AsyncAPI as a contributor to such cool things that are not just code.

#### Description

We would need something like a speaker card, that you usually have for conferences, that contains the live stream name, topic/title, date of meeting, and place for info about host and guest (including avatars)

It would be used to promote event on social media before it happens, and also as a video thumbnail afterwards.

Maybe there are also some other material that can be produces, dunno 🤷🏼 opened for any suggestions

**Comment by mcturco** [comment]
@derberg Sorry that this issue is so outdated 😅 but should we still work on these assets for the Community Meeting? As I know we changed the name from `Let's talk about Contributing`

**Comment by derberg** [comment]
@AceTheCreator created some so I close this one
