### ISSUE TITLE
Update presentation deck/template with new branding

### ISSUE THREAD

**Issue by mcturco** [asyncapi/brand#40]
#### Reason/Context
requested by @derberg 

We need to update the [AsyncAPI Deck](https://docs.google.com/presentation/d/10jFwnTckBJQFrQhgDW3a_3dL1eckQk0hxKk2e84XFJc/edit#slide=id.gc30ecbca5f_0_102) to match the new visual style.

Question for @derberg: Just so I am fully understanding this request, should I update this whole presentation with the content that is there, or should I create a presentation template with the new branding? Or both? 😄

**Comment by derberg** [comment]
I meant to update the styling of the slide deck, colors and logo to match current brand, that is it. I'm not sure how technically you would do it so hard for me to specify requirements. Let me answer this way: this slide deck is not a typical slide deck anyone uses 1:1. It is a template slide deck, we recommend it to people to take this slide deck and cut out what they want, add what they want in their copy, but just follow branding. So this slide deck is like a collection of different slides about asyncapi that now always are useful for presenter. Does it make sense? so basically entire slide deck needs to be update as it is considered to be a template for others

**Comment by mcturco** [comment]
@derberg yep that makes sense! Thanks for clarifying, I wasn't sure if the deck was used as a pitch deck for AsyncAPI for sponsorships or whatever the case may be. But thanks again for clarifying, I'm on it!

**Comment by derberg** [comment]
Deck updated: https://docs.google.com/presentation/d/10jFwnTckBJQFrQhgDW3a_3dL1eckQk0hxKk2e84XFJc/edit#slide=id.g157fdc721db_0_12
