### ISSUE TITLE
Create a banner for AsyncAPI Mentorship Program

### ISSUE THREAD

**Issue by imabp** [asyncapi/brand#58]
@mcturco, as we discussed in slack.

We have started our AsyncAPI Mentorship Program 2022. Only thing that we are missing is having a banner, that one can showcase in the socials.

**Comment by mcturco** [comment]
## Assets created for socials

### Social post 1:1
![Image](https://user-images.githubusercontent.com/60163079/173110059-db6ad205-aef0-42a8-8a9e-76ab0a5bb2ff.png)
![Image](https://user-images.githubusercontent.com/60163079/173110060-67196f2e-3ed6-4c82-84c8-da5b105f95db.png)
![Image](https://user-images.githubusercontent.com/60163079/173110057-35952828-b77f-4d53-8fdf-2ecf444636a8.png)
![Image](https://user-images.githubusercontent.com/60163079/173110056-eee824d8-759d-40cb-982e-850103a899d2.png)

### Twitter Header
![Image](https://user-images.githubusercontent.com/60163079/173110149-9af33185-8126-4cdd-9ba6-4c39fc871789.jpg)
![Image](https://user-images.githubusercontent.com/60163079/173110150-dfd8f59f-72ea-4df8-9e30-6c21e198b54d.jpg)
![Image](https://user-images.githubusercontent.com/60163079/173110152-80ed852c-286c-4985-be95-4cf23d1b1f93.jpg)
![Image](https://user-images.githubusercontent.com/60163079/173110151-4f170c2f-04d1-43d6-a553-028e28b78c96.jpg)

### LinkedIn Cover
![Image](https://user-images.githubusercontent.com/60163079/173110202-f41dda81-e67c-42c5-9795-99c8f1dd5c60.jpg)
![Image](https://user-images.githubusercontent.com/60163079/173110204-1f933993-cdd2-4a0c-8eec-31a4fce8b33f.jpg)
![Image](https://user-images.githubusercontent.com/60163079/173110201-69843743-4e0d-4f9a-a997-4661cfdac961.jpg)
![Image](https://user-images.githubusercontent.com/60163079/173110203-2854bae3-a656-4def-8cc7-cafcf500d995.jpg)
