### ISSUE TITLE
GSoD mentees swag idea

### ISSUE THREAD

**Issue by alequetzalli** [asyncapi/brand#60]
### Contribution Ask: GSoD 2022 swag 😬✌🏽
Missy designed some neat mentee swag for the **AsyncAPI 2022 Mentorship** program. Because GSoD mentees should also receive AsyncAPI swag, I was hoping we could ask for a design contribution for the GSoD mentees' swag.

### Timeline ✨
If approved, whenever? 😄😂

### Delivery process
To be handled separately from **design**; it will be a follow-up item with @Barbanio after/if/when design approves taking up this task

**Comment by alequetzalli** [comment]
@mcturco @Barbanio @fmvilas @derberg Hey folks, was talking with our lovely GSoD folks and @thulieblack made a really good suggestion. She explained she would love to have a **hoodie** instead of a t-shirt for swag. (When she said that, basically everyone in the call got excited and seconded her idea.) 

Since everyone in '22 GSoD REALLLLYYYYYY wants/hopes for a hoodie, can we make this happen for them?

**Comment by mcturco** [comment]
> Since everyone in '22 GSoD REALLLLYYYYYY wants/hopes for a hoodie, can we make this happen for them?

All for having a hoodie instead of a t-shirt 🤩 Next question is, does everyone prefer a zip-up hoodie or a pullover?

**Comment by nelsonmic** [comment]
> > Since everyone in '22 GSoD REALLLLYYYYYY wants/hopes for a hoodie, can we make this happen for them?
> 
> All for having a hoodie instead of a t-shirt 🤩 Next question is, does everyone prefer a zip-up hoodie or a pullover?

Definitely a pullover for me 😄

**Comment by thulieblack** [comment]
I prefer a pull-over, not sure about others though.

**Comment by pratik2315** [comment]
> > Since everyone in '22 GSoD REALLLLYYYYYY wants/hopes for a hoodie, can we make this happen for them?
> 
> All for having a hoodie instead of a t-shirt 🤩 Next question is, does everyone prefer a zip-up hoodie or a pullover?

Pullover for me as well😁!

**Comment by Florence-Njeri** [comment]
> > Since everyone in '22 GSoD REALLLLYYYYYY wants/hopes for a hoodie, can we make this happen for them?
> 
> All for having a hoodie instead of a t-shirt 🤩 Next question is, does everyone prefer a zip-up hoodie or a pullover?

I also prefer a pullover

**Comment by Barbanio** [comment]
Yes, I think we should unify this type of swag with all kinds of programs. We could use Printful, the company we have been using this year. What budget do we have for this?

**Comment by mcturco** [comment]
Hi! I have a rough composition of what I think could work on a hoodie for this Swag piece. Let me know if you all like this art direction and I can work to refine the details!

![GSOD_Concept](https://user-images.githubusercontent.com/60163079/174915758-9e73cdb3-e409-4c9c-918e-2b644f230033.jpg)

**Comment by alequetzalli** [comment]
The main thing that comes to mind is …I wonder if we can make sure to reference not just Google but also AsyncAPI 😬🎈🎈🌈

**Comment by thulieblack** [comment]
This is beautiful indeed, but I do agree with Ale. It would be great if it could be more of AsyncAPI than GSoD 💜

**Comment by Barbanio** [comment]
One hoodie would cost approximately $50, including shipping. Having different designs makes the products more expensive. The more products we buy, the cheaper they will be. What if we have one design for all programs? GsoD, Ambassadors, AsyncAPI Mentors...?

**Comment by derberg** [comment]
6 mentees from GSoC, 10 AsyncAPI mentorship, approx 6 mentors = at least $1200 and we cannot use our delivery we work on atm as this requires preorder of at least 50 items.

As @Barbanio wrote. Maybe we are to ambitious here, and to custom. Maybe we should have one design like "AsyncAPI Intern" for all long running mentorship programs (we can then use it for outreachy too once we get accepted) and one design like "AsyncAPI Community Hero" that we would only give away to mentors or ambassadors. And yes, "community hero" is just a name I quickly invented

**Comment by alequetzalli** [comment]
Let's just make sure we do not actually use the phrase **community hero** because that is the literal term that AWS uses for their program.

So we should make sure that we use our own unique term for our community members.

**Comment by alequetzalli** [comment]
@Barbanio @derberg Completely agree, unifying a design across several programs we run through the year is the best bet for budgetary concerns in swag production. 

I think that it makes sense for one of the designs to be either "asyncAPI Intern" or "asyncapi mentee" across our diff programs like GSoD, GSoC, and our own mentorship program. This way we do not have to create a design specifically for the different programs and this should definitely bring down production costs.

**Comment by alequetzalli** [comment]
@Barbanio Have you considered Custom Ink? Are used this production company for my own organization swag when I had to mass produce four different conferences and events we ran.


They ship internationally and most orders have a smaller minimum number of 25 or 26, was just considerably smaller than other companies that request a minimum of 50 or more products.

Ex:
https://www.customink.com/products/sweatshirts/hoodies/hanes-ecosmart-50-50-pullover-hoodie/119900


![image](https://user-images.githubusercontent.com/19964402/175064072-953641a0-4e42-4f03-b97d-4c7c0724aa5f.png)

**Comment by mcturco** [comment]
I agree, we should just use one artwork for mentees of all programs. Would it make sense to just use this graphic then?

![Screen Shot 2022-06-22 at 11 05 03 AM](https://user-images.githubusercontent.com/60163079/175064326-cf1ce409-fa4d-4a49-a758-1121be0e45e2.png)

**My thoughts about it:**
- "Mentorship Program" is a pretty general name, I know it represents the program we are running to replace GSoC, but wouldn't it be cool if it was a blanket term for all the programs that we have mentees for?
- This design can be in full color and in one color, a one-color print usually means less costs. And we can print the one color version in different colors
- This badge represents AsyncAPI
- I think a lot of people are excited about this design already

Let me know what you guys think!

**Comment by alequetzalli** [comment]
> - "Mentorship Program" is a pretty general name, I know it represents the program we are running to replace GSoC, but wouldn't it be cool if it was a blanket term for all the programs that we have mentees for?


I love the idea of using this design that you already created across all of our programs because I do think it represents asyncAPI well and the design is beautiful.

I just don't feel 100% convinced about keeping the phrase mentorship program phrase on it because I think that's confusing given the fact that we have a program called that.

My vote would be to select one phrase to represent all programs across the board and without causing confusion.

**Comment by mcturco** [comment]
> I just don't feel 100% convinced about keeping the phrase mentorship program on it because I think that's confusing given the fact that we have a program called that.

Gotcha! Or, we could simply replace "Mentorship Program" text with "AsyncAPI Initiative" and then the "Mentee" text can stay there. And we can either choose to leave the year there and get a new printing screen every year, or we can replace that with something else.

**Comment by alequetzalli** [comment]
@mcturco Oh I have to admit that I do love the idea of having the shirts include the year number if possible, based on production cost constrictions of course.

That's another good idea… We could simply say asyncAPI initiative and keep it simple by only adding "**mentee**." 🤔 curious to see what other people in the community vote on this.

**Comment by Barbanio** [comment]
> I think that it makes sense for one of the designs to be either "asyncAPI Intern" or "asyncapi mentee" across our diff programs like GSoD, GSoC, and our own mentorship program

@alequetzalli What if the term also encompasses the Ambassador Program? Then we would only have one word for all the programs, and we could reduce costs even more. I can't think of a name, any suggestions?

On the other hand, I would also remove the year in the design. I love it, but I think it's more realistic to make it as efficient as possible. For example, if we order 50 hoodies and have three left this year, we wouldn't be able to use them for next year. What do you think?

> @Barbanio Have you considered Custom Ink? I used this production company for my own organization swag when I had to mass produce for different conferences and events we ran.

It seems a good option,  but we are currently working to create the new AsyncAPI store with Pinnacle Branding, the company with which the Linux Foundation works. I think it would be ideal to work all swags with the same company, not only for management purposes but also because they will know more about the project's image. While this materializes, for small orders, we are using Printful, which does not have a minimum number of orders.

**Comment by mcturco** [comment]
> On the other hand, I would also remove the year in the design. I love it, but I think it's more realistic to make it as efficient as possible. For example, if we order 50 hoodies and have three left this year, we wouldn't be able to use them for next year. What do you think?

This is a very valid point. I've made an option without the year

![AsyncAPI_Mentee_Art_OC_FC_v2](https://user-images.githubusercontent.com/60163079/175101139-6016ab7e-627b-458e-ae89-320855c2e87c.jpg)

**Comment by derberg** [comment]
> Let's just make sure we do not actually use the phrase community hero because that is the literal term that AWS uses for their program.

omg I forgot @mcturco already have a great name and a design -> Community Gardener!!! very original, and can by a give away to mentors and ambassadors!

just a question: what is a better phrase for mentorship participants, `Mentee` or `Intern`? isn't `Inter` like more "professional" that they might prefer more? in the end, it is not much different than an internship really, something @alequetzalli opened my eyes too when you did recruitment for GSoD. I was always afraid of saying internship, but in the end, it is, right? what do you think?

**Comment by mcturco** [comment]
> omg I forgot @mcturco already have a great name and a design -> Community Gardener!!! very original, and can by a give away to mentors and ambassadors!

Should we only reserve that theme for the Ambassadors so it feels like a "special club"? I understand the problem with keeping costs down, but IMO Mentees and Ambassadors should remain separate because maybe there is a case where the Ambassador is not a Mentee and vice versa. 

> just a question: what is a better phrase for mentorship participants, Mentee or Intern? isn't Inter like more "professional" that they might prefer more? in the end, it is not much different than an internship really, something @alequetzalli opened my eyes too when you did recruitment for GSoD. I was always afraid of saying internship, but in the end, it is, right? what do you think?

Valid thought! Maybe we should ask the Mentees of the Mentorship Program and see what they would prefer. "Intern" is a better front-facing term for those trying to add experience to their resume, so maybe we should just use this instead. So it would read "AsyncAPI Initiative Intern" in the design, and then they can share this on linked in 😄

**Comment by derberg** [comment]
> Should we only reserve that theme for the Ambassadors so it feels like a "special club"? I understand the problem with keeping costs down, but IMO Mentees and Ambassadors should remain separate because maybe there is a case where the Ambassador is not a Mentee and vice versa.

hmmm, I wrote `give away to mentors and ambassadors` not mentees, for mentees you have other design, generic enough for all different mentorship programs. For Gardener I mean to share it between Ambassadors and Mentors (that is also a special club, just few folks really)

> Hmmm yeah @derberg i'm kind of thinking that it might be better if we use the word intern over mentee too 🤔... I think that the word internship will help them in their job searches more.

exactly! and `Maybe we should ask the Mentees of the Mentorship Program and see what they would prefer`

**Comment by mcturco** [comment]
> hmmm, I wrote give away to mentors and ambassadors not mentees, for mentees you have other design, generic enough for all different mentorship programs. For Gardener I mean to share it between Ambassadors and Mentors (that is also a special club, just few folks really)

Okay, I think at that point then we should just make all Mentors -> Ambassadors (Community Gardeners) to keep it simple. We don't want to use the term "Community Gardener" to represent all different groups of people as I feel like that could get confusing. So, they will still be considered Mentors in the Mentorship program, but they will be invited to the Ambassador Program as well. Does that idea make sense?

**Comment by derberg** [comment]
oh, I know what you mean, but not sure I agree 😄 

Ambassadors are like normal ambassadors, out there, in front of users, helping to spread message about AsyncAPI and educate users. They have swag packs and stuff like that. 

Mentors have totally different impact, so they would get just a hoodie without all the other goodies Ambassadors get

**Comment by Barbanio** [comment]
Yes, I think the work between mentors and ambassadors is very different. I understand the Ambassador Program as the high of contributors level, so I think the recognition should be higher.

**Comment by mcturco** [comment]
> Ambassadors are like normal ambassadors, out there, in front of users, helping to spread message about AsyncAPI and educate users. They have swag packs and stuff like that.

> Mentors have totally different impact, so they would get just a hoodie without all the other goodies Ambassadors get

@derberg Interesting 🤔 Because before you were suggesting that we should call both Ambassadors and Mentors `Community Gardeners` which was my point that they should be separate because they are different groups. I could be confused, but I think a simple solution is to just do the following:

- **Ambassadors (Ambassador Program)** --> Community Gardeners (using the gardening theme for swag)
- **Mentors (Mentorship Program)** --> [Some other "fun" name?] (IMO, mentors should get one "Mentor" branded swag item like a t-shirt along with some stickers)
- **Mentees (Mentorship Program, GSoD)** --> Interns (Intern-branded swag item, etc)

Maybe it would help to have this discussion over a live stream? That way we can make a decision together faster than back and forth messages, and then move forward with a design plan.

> Yes, I think the work between mentors and ambassadors is very different. I understand the Ambassador Program as the high of contributors level, so I think the recognition should be higher.

@Barbanio agreed! This is why I think we should reserve the `Community Gardeners` title/theme for this highest level of recognition as an incentive to want to become an ambassador instead of being called something that is shared with other groups.

**Comment by derberg** [comment]
So the thing is that Ambassador and Mentorship are different programs. But for me, at least from my perspective, it doesn't conflict with `Community Gardeners`. `Community Gardeners` is just a label, that together with carrot and other stuff just looks nice, and consistent, and in docs we can clearly say:

> `Community Gardeners` are folks in the community that help to grow and maintain the community, by being involved in different AsyncAPI programs

and just list down rules, that is it, clearly write that Mentors just get a hoodie while Ambassadors get a hoodie and other goodies (he he).

> Maybe it would help to have this discussion over a live stream? That way we can make a decision together faster than back and forth messages, and then move forward with a design plan.

we can definitely come up with proposal quicker during live stream but not make a decision there 😉

**Comment by Barbanio** [comment]
@mcturco Yes, I understand what you are saying, and I think it makes sense. I even like that idea better than the unification of the design for both programs. I defend it to make it more efficient and reduce costs.

>     Community Gardeners are folks in the community that help to grow and maintain the community, by being involved in different AsyncAPI programs
> 
> and just list down rules, that is it, clearly write that Mentors just get a hoodie while Ambassadors get a hoodie and other goodies (he he).

This sounds good, and I think the Community Gardeners concept fits well with this idea.

**Comment by derberg** [comment]
Lemme try summarizing this thread. We discuss hoodies for different parties:

1. Mentees from different long-running mentorship programs (like AsyncAPI Mentorship or GSoD or Outreachy)
2. Mentors involved in these programs
3. ​Ambassadors

Ad1.

I think we  have a clear agreement  that, we want one design - the one that @mcturco already created, and it will say `AsyncAPI Initiative Intern`

Ad2.

Here we have more opinions. 

A. either we do Mentors and Ambassadors separate
B. or we do Community Gardener for both

Motivation for **A** as far as I understand is that Ambassador swag was supposed to be unique. I just want to add that it will be anyway, as ambassadors do not only get a hoodie but a huge pack of different swags worth over $100

Morivation for **B** is that we have some limits in budget. We want to organize everything with the Swag store we want to start cooperating with. There we need to buy at least 50 hoodies, which means $1885. So calculation is simple, if we go with separate hoodie for Mentors and separate hoodie for Ambassadors then we need to order 100 hoodies, which is almost $4k. And this is a lot as we have more spending related to setup of the swag store + we do mentorship this year forth $15k and also organize a conference in person. So yeah 😅 

Do we really need to go with **A**, I really believe that design from @mcturco for Community Gardener is a perfect umbrella for a swag that is for Ambassadors and Mentors.

**Alternative:**
We do not give swags to mentors, and `mentorship` is simply one of 4 activities that count for an Ambassador (more info https://github.com/asyncapi/community/pull/361/files)

Maybe **Alternative** solution would be the best in the end? and `Community Gardener` is only for Ambassadors

**Comment by mcturco** [comment]
Thank you SO much @derberg for your detailed recap 🙌 

> Do we really need to go with A, I really believe that design from @mcturco for Community Gardener is a perfect umbrella for a swag that is for Ambassadors and Mentors.

I am fine with B after giving it some thought... we should just make sure then that we have some budget left over for "normal" swags, like logo tees and such

**Comment by Barbanio** [comment]
@derberg, thank you for the summary!

I agree with @mcturco, and I think the best choice is option B because it is more efficient than option A and there are swags for Mentors too.

**Comment by derberg** [comment]
@alequetzalli thoughts?

**Comment by alequetzalli** [comment]
I'm gonna go ahead and vote for the financially smoother option of...
`B. or we do Community Gardener for both`

**Comment by derberg** [comment]
awesome, @Barbanio will update the budget and we can prepare in next days for TSC voting on setting up a kick-ass swag store 💪🏼

**Comment by Barbanio** [comment]
Sure! I'm waiting to know the price of printing these hoodies. As soon as I have this information will update the budget 🙂
