### ISSUE TITLE
Banners for AsyncAPI conference

### ISSUE THREAD

**Issue by derberg** [asyncapi/brand#61]
Hey we need some banners for AsyncAPI Conf CfP form

Technical requirement:
        • 1040x84 - this will be used for the landing page of the CFP portal
	• 632x84 - this will be used for all other pages on the submission form

- for now we just need proper brand color and text AsyncAPI Conference 2022
- long term we can do something nicer with info about conference date

**Comment by mcturco** [comment]
@derberg Here are some banners. You'll see one size at 1x and one at 2x in case it looks blurry when added into the CfP. Let me know if there is anything else you need regarding this topic!

## 632x84

**@ 1x**
![AsyncAPIConf2022-CfP_Banner-Small@1x](https://user-images.githubusercontent.com/60163079/173658927-7a99035a-9f00-4eab-987c-16d6efc704d1.png)

**@2x**
<img width="632" alt="AsyncAPIConf2022-CfP_Banner-Small@2x" src="https://user-images.githubusercontent.com/60163079/173658934-d682dbc3-1789-4240-9eee-34e8f2f83451.png">

---

## 1040x84

**@ 1x**
![AsyncAPIConf2022-CfP_Banner-Large@1x](https://user-images.githubusercontent.com/60163079/173658936-7fcb83d2-3eb7-4976-90ae-2d8235bbb4bb.png)

**@2x**
<img width="1040" alt="AsyncAPIConf2022-CfP_Banner-Large@2x" src="https://user-images.githubusercontent.com/60163079/173658937-4b86ea96-1dfc-4130-a021-5cd61e2598fb.png">

**Comment by derberg** [comment]
@mcturco 💯 🙇🏼 🚀
