### ISSUE TITLE
some additional graphics for AsyncAPI Conference 🙏🏼 

### ISSUE THREAD

**Issue by derberg** [asyncapi/brand#67]
@mcturco we need some more graphics for AsyncAPI Conference:

```
Email & SSO Image: 1000 x 200 (JPG/PNG)
An image containing event name, event location, and event dates
"AsyncAPI Conference - Virtual - November 3-5 2022" 

Header Image: 1920 x 500 (JPG/PNG)
A background-only image that allows for Cvent text to be added over it.
```

There are all for the event registration platform.

**Comment by mcturco** [comment]
@derberg Great, I will get right on this! Question: for the header image, is there an example that will show how text will be displayed over it? Just want to make sure that I create the background so it is legible and accessible

**Comment by derberg** [comment]
@mcturco not really, sorry 😞

**Comment by mcturco** [comment]
Here's the one for `Email & SSO Image: 1000 x 200`
![AsyncAPIConf2022-SocialBanner](https://user-images.githubusercontent.com/60163079/188956380-5da05e09-b7be-4282-8e1a-9a093d1159a4.png)

For the other one, it would help to know how this asset will be used so I can make sure I am designing it properly. Can we find out more details other than `background-only image that allows for Cvent text to be added over it.` 😄

**Comment by derberg** [comment]
@mcturco I have more details from LF

```
Is it an option to have the purple graphics portion on the left and right side, leaving the center open? If you have a couple of options, I'm happy to test them out in our system and see what works best with your current design scheme.
```

also example 👇🏼 

<img width="1396" alt="Screen Shot 2022-09-09 at 9 43 05 PM" src="https://user-images.githubusercontent.com/6995927/189739791-64a99aad-dc59-4d5e-a617-85a668dc8db2.png">

**Comment by mcturco** [comment]
@derberg gotcha, thanks for asking about that! Just so I know all the details, are they planning on adding the text over top of our design as live text? Because if that is not the case, I think it would be better if I could provide the image with the text already added so we make sure it matches with the art direction of the conference this year. 

I'm also wondering if it is absolutely necessary to center the text or if it can stay left aligned?

**Comment by derberg** [comment]
technically they add text, and it must be centered

**Comment by mcturco** [comment]
Gotcha. Let me know if this works:

![AsyncAPIConf2022-LFBanner](https://user-images.githubusercontent.com/60163079/189946686-6ea54217-95bc-47e2-8c9c-515e9c751ad7.png)

**Comment by derberg** [comment]
This one is done
