### ISSUE TITLE
Access to Figma file

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/brand#71]
I thought if we have a brand/design system, why don't we have the link to the Figma file published for public access(read-only)? We can put it somewhere in the READme 

cc @mcturco

**Comment by mcturco** [comment]
We do have this published in Figma Community: https://www.figma.com/community/file/1063884118307396147

And the brand guidelines are written in markdown in the README of this file :)

**Comment by AceTheCreator** [comment]
Can we make the link to the figma community present somewhere in the READme?

**Comment by AceTheCreator** [comment]
Can we make the link to the figma community present somewhere in the READme?
