### ISSUE TITLE
New repo banner request for EDAVisualizer

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/brand#80]
Title: EDAVisualiser
Link: https://github.com/asyncapi/EDAVisualiser

**Comment by mcturco** [comment]
@jonaslagoni Here ya go! Let me know if you need anything else for this

<img width="830" alt="Github_RepoBanner_EDAVisualiser" src="https://user-images.githubusercontent.com/60163079/203328336-cbad06c0-c3dc-4d12-aa72-3673155e91a6.png">

**Comment by derberg** [comment]
@mcturco maybe you can commit to the repo as source file, a template for these? and mention in readme? is it SVG, PSD or some other Figma format?

**Comment by jonaslagoni** [comment]
Thanks @mcturco 🔥

**Comment by mcturco** [comment]
@derberg its in Figma so not sure if that would work very well

**Comment by jonaslagoni** [comment]
Closing as that conversation probably need to happen in another issue 😄

**Comment by derberg** [comment]
@mcturco so at least figma file? maybe?
