### ISSUE TITLE
New repo banner request for Java Spring Template

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/brand#93]
Hello

Could you please make a repo banner for the [Java Spring Template](https://github.com/asyncapi/java-spring-template) ?

**Comment by Tenischev** [comment]
Required for #asyncapi/java-spring-template/pull/340

**Comment by Mayaleeeee** [comment]
Of course, here it is. Please feel free to ask if you need anything else. I apologize for the delayed response; I've been occupied with other tasks.

![Github_RepoBanner_JavaSpringGenerator](https://github.com/asyncapi/brand/assets/105395613/0775c1e2-8134-452d-9cbd-24c959bcda0a)
